### ISSUE TITLE
read in D0x files

### ISSUE THREAD

**Issue by bjarthur** [HySonLab/ML4Insects#3]
feature request:  would be nice to be able to read in the .D0x (or even .aq8) files instead of .A0x.  those files are binary and so have a smaller footprint on disk.  and it's just one more step users have to take to generate the .A0x files.

**Comment by bjarthur** [comment]
```
    d = np.fromfile(file_path+'.D01', dtype=np.float32)
    df = pd.DataFrame(d, columns=[1])
```

**Comment by bjarthur** [comment]
should rather be:

```
fid = open(file_path, 'rb')
fid.readline();  fid.readline();  fid.readline();
x = pd.DataFrame(np.fromfile(fid, dtype=np.float32), columns=[1])
fid.close()
```

and should go roughly [here](https://github.com/HySonLab/ML4Insects/blob/main/package/DiscoEPG/dataset_utils/datahelper.py#L46).  i can submit a PR if you like.

**Comment by DINHQuangDung1999** [comment]
Thank you, Ben! This is such a great help, and it boost the data loading time by a few times! In fact, I thought of this during the development process, but I encountered some errors that I was not able to figure out. Please find the update in the latest version  `pip install DiscoEPG==0.0.16`!
