### ISSUE TITLE
error reading in .ANA files

### ISSUE THREAD

**Issue by bjarthur** [HySonLab/ML4Insects#4]
working through the visualization tutorial, i got "UTF-16 stream does not start with BOM" when calling `datahelper.read_signal`.  i fixed it by removing the "encoding" input arg [here](https://github.com/HySonLab/ML4Insects/blob/main/package/DiscoEPG/dataset_utils/datahelper.py#L54)/

**Comment by DINHQuangDung1999** [comment]
I added a `try except` block for handling this
